In [1]:
%reload_ext taegis_magic

In [2]:
%taegis -h

usage: taegis_magic_parser [-h] [--assign NAME | --append NAME]
                           [--display NAME]
                           [--disable-return-display {off,all,on_empty}]
                           [--cell CELL] [-t] [-f CELL_TEMPLATE_FILE]
                           [--cache]

options:
  -h, --help            show this help message and exit
  --assign NAME         Assign results as pandas DataFrame to NAME
  --append NAME         Append results as pandas DataFrame to NAME
  --display NAME        Display NAME as markdown table
  --disable-return-display {off,all,on_empty}
                        Disable automatic display of return metadata table,
                        does not work with --cache
  --cell CELL           Cell contents
  -t, --cell-template   Use a Jinja2 Template for input, uses Shell Namespace
                        as variables
  -f, --cell-template-file CELL_TEMPLATE_FILE
                        Use a template file instead of providing cell input
  --cache               Save output to cache / Load output from cache (if
                        present)

 Usage: taegis [OPTIONS] COMMAND [ARGS]...

 Taegis Magic help menu.

╭─ Options ───────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --warning                 --no-warning          Set taegis_magic logger level for this command.                 │
│                                                 [default: no-warning]                                           │
│ --verbose                 --no-verbose          Set taegis_magic logger level for this command.                 │
│                                                 [default: no-verbose]                                           │
│ --debug                   --no-debug            Set taegis_magic logger level for this command.                 │
│                                                 [default: no-debug]                                             │
│ --trace                   --no-trace            Set taegis_magic logger level for this command.                 │
│                                                 [default: no-trace]                                             │
│ --error                   --no-error            Set taegis_magic logger level for this command.                 │
│                                                 [default: no-error]                                             │
│ --sdk-warning             --no-sdk-warning      Set taegis_sdk_python logger level for this command.            │
│                                                 [default: no-sdk-warning]                                       │
│ --sdk-verbose             --no-sdk-verbose      Set taegis_sdk_python logger level for this command.            │
│                                                 [default: no-sdk-verbose]                                       │
│ --sdk-debug               --no-sdk-debug        Set taegis_sdk_python logger level for this command.            │
│                                                 [default: no-sdk-debug]                                         │
│ --sdk-error               --no-sdk-error        Set taegis_sdk_python logger level for this command.            │
│                                                 [default: no-sdk-error]                                         │
│ --install-completion                            Install completion for the current shell.                       │
│ --show-completion                               Show completion for the current shell, to copy it or customize  │
│                                                 the installation.                                               │
│ --help                -h                        Show this message and exit.                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─ Commands ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ version          Taegis Magic version information.                                                              │
│ alerts           Taegis Alerts Commands.                                                                        │
│ auth             Taegis Authentication Commands.                                                                │
│ audits           Taegis Audit Commands.                                                                         │
│ clients          Taegis Clients Commands.                                                                       │
│ configure        Taegis Magic Configuration Commands.                                                           │
│ events           Taegis Events Commands.                                                                        │
│ investigations   Taegis Investigation Commands.                                                                 │
│ notebook         Taegis Notebook Commands.                                                                      │
│ preferences      Taegis Preferences Commands.                                                                   │
│ rules            Taegis Rules Commands.                                                                         │
│ search           Taegis Search Commands.                                                                        │
│ sharelinks       Taegis Sharelinks Commands.                                                                    │
│ subjects         Taegis Subjects Commands.                                                                      │
│ tenant-profiles  Taegis Tenant Profile Commands.                                                                │
│ tenants          Taegis Tenant Commands.                                                                        │
│ threat           Taegis Threat Intelligence Commands.                                                           │
│ users            Taegis User Commands.                                                                          │
│ process-trees    Taegis Process Trees Commands.                                                                 │
│ query            Taegis Query Commands.                                                                         │
│ orchestration    Taegis Orchestration Commands.                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [3]:
from taegis_sdk_python.config import write_to_config
write_to_config("magics.regions", "pilot", "https://api.pilot.8labs.io")

In [4]:
domains = [
    "myxavpn.pro",
    "app.myxavpn.pro",
    "getmyxa.com",
    "app.getmyxa.com",
    "myxavpn.com",
    "app.myxavpn.com",
    "myxavpn.site",
    "myxavpn.online",
    "myxavpn.tech",
    "myxasafe.space",
    "atlasvpn.space",
    "bezopasnet.space",
    "cipherway.space",
    "cloudmask.space",
    "echosecure.space",
    "gusentun.space",
    "gusenvpn.online",
    "horizonguard.space",
    "internetprvpn.ru",
    "ironproxy.space",
    "korovkavpn.space",
    "maskirovka.space",
    "murvpn.space",
    "myxasecure.space",
    "myxavpn.space",
    "neoncloak.space",
    "netroutehub.space",
    "nimbusshield.space",
    "osavpn.su",
    "pauktun.space",
    "primeproxy.space",
    "routekeeper.space",
    "routeshield.space",
    "salega.ru",
    "securepulse.space",
    "shershvpn.space",
    "shieldtunnel.space",
    "silashield.space",
    "skorostvpn.space",
    "skyproxy.space",
    "spidervpn.online",
    "stableproxy.space",
    "stealthpath.space",
    "sverchtun.store",
    "sverchvpn.space",
    "tarakanvpn.online",
    "tunnelbase.space",
    "turbotunnel.space",
    "usachvpn.su",
    "vaultvpn.space",
    "vpn-myxa.ru",
    "vpnfasters.space",
    "vpnkomar.space",
    "vpnmyha.shop",
    "vpnmyxa.site",
    "zenshield.space",
    "zhuknet.online",
    "zhukvpn.online",
    "ns1.reg.ru",
    "ns2.reg.ru",
    "badguy.zz"
    ""
]

In [5]:
import re

pattern = "|".join(rf"(^|\.){re.escape(d)}$" for d in domains)

query = f"""
WITH UniqueHosts AS (
    SELECT DISTINCT uri_host FROM http
),
MatchedHosts AS (
    SELECT uri_host FROM UniqueHosts
    WHERE regexp_like(uri_host, '{pattern}')
)
SELECT h.*
FROM http h
JOIN MatchedHosts m ON h.uri_host = m.uri_host
"""

In [6]:
print(query)

WITH UniqueHosts AS (
    SELECT DISTINCT uri_host FROM http
),
MatchedHosts AS (
    SELECT uri_host FROM UniqueHosts
    WHERE regexp_like(uri_host, '(^|\.)myxavpn\.pro$|(^|\.)app\.myxavpn\.pro$|(^|\.)getmyxa\.com$|(^|\.)app\.getmyxa\.com$|(^|\.)myxavpn\.com$|(^|\.)app\.myxavpn\.com$|(^|\.)myxavpn\.site$|(^|\.)myxavpn\.online$|(^|\.)myxavpn\.tech$|(^|\.)myxasafe\.space$|(^|\.)atlasvpn\.space$|(^|\.)bezopasnet\.space$|(^|\.)cipherway\.space$|(^|\.)cloudmask\.space$|(^|\.)echosecure\.space$|(^|\.)gusentun\.space$|(^|\.)gusenvpn\.online$|(^|\.)horizonguard\.space$|(^|\.)internetprvpn\.ru$|(^|\.)ironproxy\.space$|(^|\.)korovkavpn\.space$|(^|\.)maskirovka\.space$|(^|\.)murvpn\.space$|(^|\.)myxasecure\.space$|(^|\.)myxavpn\.space$|(^|\.)neoncloak\.space$|(^|\.)netroutehub\.space$|(^|\.)nimbusshield\.space$|(^|\.)osavpn\.su$|(^|\.)pauktun\.space$|(^|\.)primeproxy\.space$|(^|\.)routekeeper\.space$|(^|\.)routeshield\.space$|(^|\.)salega\.ru$|(^|\.)securepulse\.space$|(^|\.)shershvpn\.space$|(^|\.)shieldtunnel\.space$|(^|\.)silashield\.space$|(^|\.)skorostvpn\.space$|(^|\.)skyproxy\.space$|(^|\.)spidervpn\.online$|(^|\.)stableproxy\.space$|(^|\.)stealthpath\.space$|(^|\.)sverchtun\.store$|(^|\.)sverchvpn\.space$|(^|\.)tarakanvpn\.online$|(^|\.)tunnelbase\.space$|(^|\.)turbotunnel\.space$|(^|\.)usachvpn\.su$|(^|\.)vaultvpn\.space$|(^|\.)vpn\-myxa\.ru$|(^|\.)vpnfasters\.space$|(^|\.)vpnkomar\.space$|(^|\.)vpnmyha\.shop$|(^|\.)vpnmyxa\.site$|(^|\.)zenshield\.space$|(^|\.)zhuknet\.online$|(^|\.)zhukvpn\.online$|(^|\.)ns1\.reg\.ru$|(^|\.)ns2\.reg\.ru$|(^|\.)badguy\.zz$')
)
SELECT h.*
FROM http h
JOIN MatchedHosts m ON h.uri_host = m.uri_host

In [12]:
%taegis query search --tenant 11772 --workload "search-qee-runner" --time-range-start "2026-08-22T00:00:00Z" --time-range-end "2026-08-27T00:00:00Z" --page-size 1000 --region pilot --assign rows --cell "$query"

Executing query: 0 poll [00:00, ?poll/s]

Fetching results:   0%|          | 0/22 [00:00<?, ?rows/s]

**Taegis Results**

|Region          |Tenant             |Service          |Total Results                       |
|----------------|-------------------|-----------------|------------------------------------|
|pilot|11772|query_relay|21606|

In [13]:
rows[["resource_id", "uri_host"]].head()

                                         resource_id   uri_host
0  event://priv:scwx.http:11772:1787732931000:1ea...  badguy.zz
1  event://priv:scwx.http:11772:1787732968000:1ea...  badguy.zz
2  event://priv:scwx.http:11772:1787733083000:1ea...  badguy.zz
3  event://priv:scwx.http:11772:1787841226000:1ea...  badguy.zz
4  event://priv:scwx.http:11772:1787841402000:1ea...  badguy.zz

In [14]:
print(f"rows returned: {len(rows)}")
if not rows.empty:
    preview_cols = [c for c in ["ingest_time", "event_type", "host_id", "resource_id", "tenant_id"] if c in rows.columns]
    display(rows[preview_cols].head(10) if preview_cols else rows.head(10))
else:
    print("no events returned in the last 24 hours")

rows returned: 21606

  host_id                                        resource_id tenant_id
0          event://priv:scwx.http:11772:1787732931000:1ea...     11772
1          event://priv:scwx.http:11772:1787732968000:1ea...     11772
2          event://priv:scwx.http:11772:1787733083000:1ea...     11772
3          event://priv:scwx.http:11772:1787841226000:1ea...     11772
4          event://priv:scwx.http:11772:1787841402000:1ea...     11772
5          event://priv:scwx.http:11772:1787732961000:1ea...     11772
6          event://priv:scwx.http:11772:1787733167000:1ea...     11772
7          event://priv:scwx.http:11772:1787733165000:1ea...     11772
8          event://priv:scwx.http:11772:1787733096000:1ea...     11772
9          event://priv:scwx.http:11772:1787733098000:1ea...     11772

In [15]:
if not rows.empty:
    preview_cols = [c for c in ["ingest_time_usec", "host_id", "resource_id", "tenant_id", "original_uri"] if c in rows.columns]
    display(rows[preview_cols].head(10) if preview_cols else rows.head(10))
else:
    print("no events returned in the last 24 hours")

,ingest_time_usec,host_id,resource_id,tenant_id,original_uri
0,1787732931000000,,event://priv:scwx.http:11772:1787732931000:1ea...,11772,http://badguy.zz/
1,1787732968000000,,event://priv:scwx.http:11772:1787732968000:1ea...,11772,http://badguy.zz/
2,1787733083000000,,event://priv:scwx.http:11772:1787733083000:1ea...,11772,http://badguy.zz/
3,1787841226000000,,event://priv:scwx.http:11772:1787841226000:1ea...,11772,http://badguy.zz/
4,1787841402000000,,event://priv:scwx.http:11772:1787841402000:1ea...,11772,http://badguy.zz/
5,1787732961000000,,event://priv:scwx.http:11772:1787732961000:1ea...,11772,http://badguy.zz/
6,1787733167000000,,event://priv:scwx.http:11772:1787733167000:1ea...,11772,http://badguy.zz/
7,1787733165000000,,event://priv:scwx.http:11772:1787733165000:1ea...,11772,http://badguy.zz/
8,1787733096000000,,event://priv:scwx.http:11772:1787733096000:1ea...,11772,http://badguy.zz/
9,1787733098000000,,event://priv:scwx.http:11772:1787733098000:1ea...,11772,http://badguy.zz/